apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
spec:
  containers:
    - name: dnsutils
      image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: claims
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claims
  template:
    metadata:
      labels:
        app: claims
    spec:
      containers:
        - name: claims
          image: miguelperezcolom/claims-platform
          ports:
            - containerPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: claims
spec:
  type: ClusterIP
  selector:
    app: claims
  ports:
    - appProtocol: TCP
      port: 8081
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bowie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bowie
  template:
    metadata:
      labels:
        app: bowie
    spec:
      containers:
        - name: bowie
          image: miguelperezcolom/bowie
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: bowie-service
spec:
  type: NodePort
  selector:
    app: bowie
  ports:
    - nodePort: 30163
      port: 801
      targetPort: 8080
